trigger:
  - master
jobs:
  - job: TestCode
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
      displayName: 'Use Python 3.6'
    - script: python3 text.py